sudo: false
language: node_js
cache:
  directories:
  - node_modules
  - jspm_packages
branches:
  only:
  - master
  - /^greenkeeper/.*$/
notifications:
  email: true
node_js:
  - '4.2'
before_script:
  - npm prune
before_install:
  - npm run setup
